{
 "title": "micro-market Metrics Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "HTTP Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "rate(http_requests_received_total{}[$__interval])"
    }
   ]
  },
  {
   "title": "No Of Threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    { "expr": "process_num_threads{}" }
   ]
  },
  {
   "title": "Process Virtual Memory Bytes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    { "expr": "process_virtual_memory_bytes{}" }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 10, "w": 23, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "{app=~\".+\"}"
    }
   ]
  }
 ]
}